ccflags-y += -I$(src)/../include

obj-m += gpioctl_core_zsh.o
gpioctl_core_zsh-y := core/gpioctl_core_zsh.o

obj-m += gpioctl_backend_gpiolib_zsh.o
gpioctl_backend_gpiolib_zsh-y := backend_gpiolib/gpioctl_backend_gpiolib_zsh.o

obj-m += gpioctl_mock_zsh.o
gpioctl_mock_zsh-y := backend_mock/gpioctl_mock_zsh.o

obj-m += gpioctl_backend_phytium_zsh.o
gpioctl_backend_phytium_zsh-y := backend_phytium/gpioctl_backend_phytium_zsh.o

