# alias device offset active_low pad physical_pin description
LED20 /dev/gpio1_zsh 8 1 E37 onboard board_led20
GPIO1_11 /dev/gpio1_zsh 11 0 BA49 15 external_led_1
GPIO4_7 /dev/gpio4_zsh 7 0 W53 19 external_led_2

