# alias device offset active_low pad physical_pin description
LED20 /dev/gpio1_zsh 8 1 E37 onboard board_led20
GPIO0_0 /dev/gpio0_zsh 0 0 AN59 36 header_gpio
GPIO0_14 /dev/gpio0_zsh 14 0 AJ59 22 header_gpio
GPIO1_1 /dev/gpio1_zsh 1 0 AG57 32 header_gpio
GPIO1_5 /dev/gpio1_zsh 5 0 AR49 18 header_gpio
GPIO1_11 /dev/gpio1_zsh 11 0 BA49 15 external_led_1
GPIO1_12 /dev/gpio1_zsh 12 0 AW55 13 header_gpio
GPIO2_1 /dev/gpio2_zsh 1 0 R49 12 header_gpio
GPIO2_2 /dev/gpio2_zsh 2 0 N51 35 header_gpio
GPIO2_5 /dev/gpio2_zsh 5 0 J55 40 header_gpio
GPIO2_6 /dev/gpio2_zsh 6 0 J45 38 header_gpio
GPIO2_8 /dev/gpio2_zsh 8 0 C39 33 header_gpio
GPIO2_10 /dev/gpio2_zsh 10 0 A37 7 header_gpio
GPIO3_0 /dev/gpio3_zsh 0 0 A49 8 header_gpio
GPIO3_1 /dev/gpio3_zsh 1 0 C49 11 header_gpio
GPIO3_2 /dev/gpio3_zsh 2 0 A51 16 header_gpio
GPIO4_6 /dev/gpio4_zsh 6 0 W55 23 header_gpio
GPIO4_7 /dev/gpio4_zsh 7 0 W53 19 external_led_2
GPIO4_8 /dev/gpio4_zsh 8 0 U55 21 header_gpio
GPIO4_9 /dev/gpio4_zsh 9 0 U53 24 header_gpio
GPIO4_10 /dev/gpio4_zsh 10 0 AE49 26 header_gpio
GPIO4_11 /dev/gpio4_zsh 11 0 AC49 29 header_gpio
GPIO4_12 /dev/gpio4_zsh 12 0 AE47 31 header_gpio
GPIO4_13 /dev/gpio4_zsh 13 0 AA47 37 header_gpio
GPIO4_14 /dev/gpio4_zsh 14 0 AA49 28 header_gpio
GPIO4_15 /dev/gpio4_zsh 15 0 W49 27 header_gpio
